### ISSUE TITLE
runtime error when indexing erc 4337 entrypoint event

### ISSUE THREAD

**Issue by 0xBigBoss** [indexsupply/code#240]
I am running into the following runtime error when trying to index a specific event for  the erc 4337 [entrypoint v0.7](https://basescan.org/address/0x0000000071727De22E5E9d8BAf0edAc6f37da032#events).

Specifically the `AccountDeployed` event. I have the following config.json below.

<details>

<summary>config.json</summary>

```json
{
  "dashboard": {
    "root_password": "$DASHBOARD_ROOT_PASSWORD"
  },
  "pg_url": "$DATABASE_URL",
  "eth_sources": [
    {
      "name": "$BASE_NAME",
      "url": "$BASE_RPC_URL",
      "chain_id": "$BASE_CHAIN_ID",
      "batch_size": 100
    }
  ],
  "integrations": [
    {
      "name": "account_deployed",
      "enabled": true,
      "block": [
        {
          "name": "block_time",
          "column": "block_time"
        },
        {
          "name": "log_addr",
          "column": "log_addr",
          "filter_op": "contains",
          "filter_arg": [
            "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
          ]
        }
      ],
      "event": {
        "type": "event",
        "anonymous": false,
        "inputs": [
          {
            "name": "userOpHash",
            "type": "bytes32",
            "indexed": true
          },
          {
            "name": "sender",
            "type": "address",
            "indexed": true
          },
          {
            "name": "factory",
            "type": "address",
            "indexed": false
          },
          {
            "name": "paymaster",
            "type": "address",
            "indexed": false
          }
        ],
        "name": "AccountDeployed"
      },
      "table": {
        "name": "send_account_deployed",
        "columns": [
          {
            "name": "chain_id",
            "type": "numeric"
          },
          {
            "name": "log_addr",
            "type": "bytea"
          },
          {
            "name": "block_time",
            "type": "numeric"
          },
          {
            "name": "userOpHash",
            "type": "bytea"
          },
          {
            "name": "sender",
            "type": "bytea"
          },
          {
            "name": "factory",
            "type": "bytea"
          },
          {
            "name": "paymaster",
            "type": "bytea"
          }
        ]
      },
      "sources": [
        {
          "name": "$BASE_NAME",
          "start": "$BASE_BLOCK_START"
        }
      ]
    }
  ]
}
```

</details>

I am running shovel like so.

```shell
docker run \
  --rm \
  --name shovel \
  --add-host=host.docker.internal:host-gateway \
  -p 8383:80 \
  --env DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:54322/postgres \
  --env BASE_NAME=base \
  --env BASE_RPC_URL=https://base-pokt.nodies.app \
  --env BASE_CHAIN_ID=8453 \
  --env BASE_BLOCK_START=11135065 \
  --env DASHBOARD_ROOT_PASSWORD=shoveladmin \
  -v ./config.json:/etc/shovel/config.json \
  --entrypoint /usr/local/bin/shovel \
  -w /usr/local/bin \
  docker.io/indexsupply/shovel -l :80 -config /etc/shovel/config.json
p=1 v=5775 chain=08453 src=base dest=account_deployed msg=new-task
p=1 v=5775 n=0 msg=prune-task
p=1 v=5775 chain=08453 num=11135065 msg=start at config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4ed750]

goroutine 100 [running]:
github.com/indexsupply/x/dig.(*logWithCtx).get(0x68df80?, {0x400000fb60?, 0x0?})
	/app/dig/dig.go:834 +0x2c0
github.com/indexsupply/x/dig.Integration.processTx({{0x400000fb30, 0x10}, {0x0, {0x400000fbd0, 0xf}, {0x400000fb78, 0x5}, {0x4000258840, 0x4, 0x4}}, ...}, ...)
	/app/dig/dig.go:849 +0x13c
github.com/indexsupply/x/dig.Integration.Insert({{0x400000fb30, 0x10}, {0x0, {0x400000fbd0, 0xf}, {0x400000fb78, 0x5}, {0x4000258840, 0x4, 0x4}}, ...}, ...)
	/app/dig/dig.go:713 +0x438
github.com/indexsupply/x/shovel.(*Task).loadinsert.func1()
	/app/shovel/task.go:471 +0x128
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 18
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x98
```

Really racked my head on this one trying to ensure it wasn't me, but for the life of me I couldn't figure out why the log address is not set correctly for this event. 

https://github.com/indexsupply/code/blob/57755b46c8566f8cc8626d13319297fab0c1310e/dig/dig.go#L833-L834

**Comment by ryandotsmith** [comment]
Ah. I see the problem. The `event` fields are missing `column` fields. Because of this, Shovel thinks that there are no event/logs to index so it attempts to parse a transaction. But since `log_addr` is defined in the `block` field it is also attempting to parse log data. This is an error condition that is not handled in Shovel -- which is a bug.

However, if you make the following changes to your config file, then this should work. I tested locally to make sure that it does and it checks out.

```diff
@@ -36,22 +36,26 @@
           {
             "name": "userOpHash",
             "type": "bytes32",
-            "indexed": true
+            "indexed": true,
+            "column": "user_op_hash"
           },
           {
             "name": "sender",
             "type": "address",
-            "indexed": true
+            "indexed": true,
+            "column": "sender"
           },
           {
             "name": "factory",
             "type": "address",
-            "indexed": false
+            "indexed": false,
+            "column": "factory"
           },
           {
             "name": "paymaster",
             "type": "address",
-            "indexed": false
+            "indexed": false,
+            "column": "paymaster"
           }
         ],
         "name": "AccountDeployed"
@@ -72,7 +76,7 @@
             "type": "numeric"
           },
           {
-            "name": "userOpHash",
+            "name": "user_op_hash",
             "type": "bytea"
           },
           {
```

**Comment by ryandotsmith** [comment]
Also, i had to remove the camel case from the table column name. Postgres doesn't distinguish capitalization.

**Comment by 0xBigBoss** [comment]
Tysm for the quick response again. I had a feeling I was shooting myself in the foot. Confirming the updated config.json is working for my case. 

I think I have 2 more integrations to write after this one to index **all** sent transactions from the smart account, and a `Received` event to index received transactions on the smart account. So if you don't hear from me for awhile, just know that everything worked out. Shovel FTW!

**Comment by ryandotsmith** [comment]
OK. Great! You definitely hit a rough edge that needs to be smoothed out. Thank you for your excellent bug reports. It was a pleasure to debug.

**Comment by ryandotsmith** [comment]
BTW, I'm not sure what language you are using for your app, but in the case it is TS, would you have any interest in using the TS package to help with config creation?

https://tsdocs.dev/docs/@indexsupply/shovel-config/0.0.5

**Comment by 0xBigBoss** [comment]
> BTW, I'm not sure what language you are using for your app, but in the case it is TS, would you have any interest in using the TS package to help with config creation?
> 
> [tsdocs.dev/docs/@indexsupply/shovel-config/0.0.5](https://tsdocs.dev/docs/@indexsupply/shovel-config/0.0.5)

100%, you can see our example usage below. it's only on my feature branch for now, but so far so good.

https://github.com/0xsend/sendapp/blob/0470d38eb5d8e6fc5662f36b59fc33fc2e5b03f4/packages/shovel/src/index.ts#L35-L42
