### ISSUE TITLE
panic: close of closed channel in dig.Integration.Insert

### ISSUE THREAD

**Issue by dcposch** [indexsupply/code#260]
## Summary

We observe the following panic intermittently, every few minutes to every few hours.

Shovel version: `indexsupply/shovel:3339`
Shovel config: https://github.com/daimo-eth/daimo/blob/master/packages/daimo-contract/src/shovel/config.json

```
goroutine 32953 [running]:
github.com/jackc/pgx/v5/pgconn.(*PgConn).CopyFrom(0x40002fc000, {0x9639f8, 0x4003cff440}, {0x95c260?, 0x400005c3f0}, {0x4000dae540, 0xb5})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.5/pgconn/pgconn.go:1340 +0x804
github.com/jackc/pgx/v5.(*copyFrom).run(0x40004ba900, {0x9639f8?, 0x4003cff440?})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.5/copy_from.go:202 +0x4b8
github.com/jackc/pgx/v5.(*Conn).CopyFrom(0x40002687e0, {0x9639f8, 0x4003cff440}, {0x40004f9760, 0x1, 0x1}, {0x4000380e00, 0xc, 0x10}, {0x962370?, ...})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.5/copy_from.go:275 +0x148
github.com/jackc/pgx/v5.(*dbTx).CopyFrom(0xffff754587b8?, {0x9639f8?, 0x4003cff440?}, {0x40004f9760?, 0x40004f9760?, 0x0?}, {0x4000380e00?, 0x4f42c0?, 0x10?}, {0x962370?, ...})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.5/tx.go:256 +0x60
github.com/jackc/pgx/v5/pgxpool.(*Tx).CopyFrom(0x4000224320?, {0x9639f8?, 0x4003cff440?}, {0x40004f9760?, 0x0?, 0x0?}, {0x4000380e00?, 0x0?, 0x0?}, {0x962370?, ...})
	/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.5/pgxpool/tx.go:46 +0x40
github.com/indexsupply/x/dig.Integration.Insert({{0x4000224320, 0xd}, {0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}}, ...}, ...)
	/app/dig/dig.go:827 +0x270
github.com/indexsupply/x/shovel.(*Task).loadinsert.func1()
	/app/shovel/task.go:491 +0x25c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 65
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x98
panic: close of closed channel

```

**Comment by ryandotsmith** [comment]
A few follow up questions:

1. OS name/version
2. Postgres version
3. Are you using pg bouncer or anything other than a direct connection?

**Comment by dcposch** [comment]
1. Running docker in ECS. Same OS/version as the base indexsupply/shovel:3339 image
2. Postgres 16.2 in RDS
3. Direct connection from the container to RDS DB

**Comment by ryandotsmith** [comment]
source of panic: https://github.com/jackc/pgx/blob/v5.5.5/pgconn/pgconn.go#L1340

**Comment by ryandotsmith** [comment]
I was able to reproduce this panic locally by:

- setting connection pool size to 1
- add additional latency via `time.Sleep` to the downloading of data

I have not been able to reproduce using: #261
